spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/edustor_telegram
      username: postgres
  jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
  data:
    mongodb:
      database: edustor-telegram
flyway:
  validate-on-migrate: false